"use client";

import { BriefingPage, PRINT_COLORS } from "./BriefingChrome";

interface Props {
  pageNumber: number;
  totalPages: number;
  generatedDateLabel: string;
  briefingId: string;
  generatedAt: string;
  generatedByLabel: string;
  filterStateLabel: string;
}

export default function ColophonPage({
  pageNumber,
  totalPages,
  generatedDateLabel,
  briefingId,
  generatedAt,
  generatedByLabel,
  filterStateLabel,
}: Props) {
  const fullTimestamp = new Date(generatedAt).toLocaleString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });

  return (
    <BriefingPage
      sectionLabel="COLOPHON"
      pageNumber={pageNumber}
      totalPages={totalPages}
      generatedDateLabel={generatedDateLabel}
    >
      <div
        style={{
          flex: "1 1 auto",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          textAlign: "center",
          padding: "0 0.4in",
        }}
      >
        <h2
          style={{
            fontSize: "22pt",
            fontWeight: 600,
            letterSpacing: "-0.015em",
            lineHeight: 1.15,
            color: PRINT_COLORS.navy,
            margin: "0 0 18pt",
          }}
        >
          About this briefing
        </h2>

        <p
          style={{
            fontSize: "11pt",
            lineHeight: 1.7,
            color: PRINT_COLORS.navy,
            maxWidth: "5in",
            margin: "0 0 26pt",
          }}
        >
          This briefing was generated by IBX Co-Connect, a community engagement
          platform developed for the Interborough Express light rail study.
          Themes were synthesized using machine clustering of community-submitted
          concerns, proposals, and notes. The executive summary on page 2 was
          generated by an AI language model from the data captured in this
          snapshot. Contributions remain the property of their authors and are
          anonymized in this document. For questions, contact the planning team.
        </p>

        <div
          style={{
            fontFamily: "var(--font-jetbrains-mono), ui-monospace, monospace",
            fontSize: "9.5pt",
            color: PRINT_COLORS.navyDim,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            fontWeight: 600,
            lineHeight: 2.0,
          }}
        >
          <div>VERSION · {briefingId}</div>
          <div>GENERATED · {fullTimestamp}</div>
          <div>BY · {generatedByLabel}</div>
          <div>FILTER STATE · {filterStateLabel}</div>
        </div>
      </div>

      <div
        style={{
          textAlign: "center",
          fontFamily: "var(--font-jetbrains-mono), ui-monospace, monospace",
          fontSize: "8.5pt",
          color: PRINT_COLORS.navyDim,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          fontWeight: 600,
          paddingTop: "12pt",
          borderTop: `1px solid ${PRINT_COLORS.navyHairline}`,
        }}
      >
        IBX Co-Connect · Community Briefing System
      </div>
    </BriefingPage>
  );
}
